actions:
  post:
    gnometerminal: zsh -c 'dconf load '/org/gnome/terminal/' < ~/.gnome-terminal-profile'
    gitconfig: sh ~/.scripts/set-gitconfig
    oh-my-zsh: zsh -c 'if [[ -d ~/.oh-my-zsh ]]; then (cd ~/.oh-my-zsh && git pull);
      else (git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh);
      fi && if [[ -d ~/.dracula-zsh-theme ]]; then (cd ~/.dracula-zsh-theme && git pull); else (git clone https://github.com/dracula/zsh.git ~/.dracula-zsh-theme); fi
      && cd ~/.oh-my-zsh/themes && ln -sf ~/.dracula-zsh-theme/dracula.zsh-theme && ln -sf ~/.dracula-zsh-theme/lib'
    vim-plugins: curl -fLo ~/.vim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      && vim +':PlugInstall' +'PlugUpdate' +':q' +':q' && reset && clear
    gtk: zsh -c 'if [[ -d ~/.themes/dracula ]]; then (cd ~/.themes/dracula && git pull); else (git clone
      https://github.com/dracula/gtk.git ~/.themes/dracula); fi'
    tmux: zsh -c 'if [[ -d ~/.tmux/plugins/tpm ]]; then (cd ~/.tmux/plugins/tpm && git pull); else (git clone
      https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm); fi && ~/.tmux/plugins/tpm/bin/install_plugins && ~/.tmux/plugins/tpm/bin/update_plugins all'
config:
  backup: true
  banner: false
  create: true
  dotpath: files
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_tmux.conf:
    actions:
    - tmux
    dst: ~/.tmux.conf
    link: link
    src: tmux.conf
  f_vimrc:
    actions:
    - vim-plugins
    dst: ~/.vimrc
    link: link
    src: vimrc
  f_zshenv:
    dst: ~/.zshenv
    link: link
    src: zshenv
  f_zshrc:
    actions:
    - oh-my-zsh
    dst: ~/.zshrc
    link: link
    src: zshrc
  d_scripts:
    actions:
    - gitconfig
    src: scripts
    dst: ~/.scripts
    link: link
  a_gnometerminal:
    dst: ~/.gnome-terminal-profile
    src: gnome-terminal-profile
    actions:
    - gnometerminal
  a_gtk:
    src:
    dst:
    actions:
    - gtk
profiles:
  default:
    dotfiles:
    - a_gnometerminal
    - a_gtk
    - d_scripts
    - f_zshenv
    - f_zshrc
    - f_vimrc
    - f_tmux.conf
