actions:
  post:
    gitconfig: sh ~/.scripts/set-gitconfig
    tmux: zsh -c 'if [[ -d ~/.tmux ]]; then (cd ~/.tmux && git pull); else (git clone
      https://github.com/gpakosz/.tmux.git ~/.tmux); fi && ln -sf ~/.tmux/.tmux.conf
      ~/.tmux.conf'
    oh-my-zsh: zsh -c 'if [[ -d ~/.oh-my-zsh ]]; then (cd ~/.oh-my-zsh && git pull);
      else (git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh);
      fi'
    vim-plugins: curl -fLo ~/.vim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      && vim +':PlugInstall' +'PlugUpdate' +':q' +':q' && reset && clear
config:
  backup: true
  banner: false
  create: true
  dotpath: files
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: link
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_tmux.conf.local:
    actions:
    - tmux
    dst: ~/.tmux.conf.local
    link: link
    src: tmux.conf.local
  f_vimrc:
    actions:
    - vim-plugins
    dst: ~/.vimrc
    link: link
    src: vimrc
  f_zshenv:
    dst: ~/.zshenv
    link: link
    src: zshenv
  f_zshrc:
    actions:
    - oh-my-zsh
    dst: ~/.zshrc
    link: link
    src: zshrc
  d_scripts:
    actions:
    - gitconfig
    src: scripts
    dst: ~/.scripts
    link: link
profiles:
  default:
    dotfiles:
    - d_scripts
    - f_zshenv
    - f_zshrc
    - f_vimrc
    - f_tmux.conf.local
