#!/usr/bin/env sh

PYTHON_BIN="python3"
PYTHON=`which "$PYTHON_BIN" > /dev/null 2>&1; echo "$?"`

if [ "$PYTHON" != "0" ]; then
    echo "> '$PYTHON_BIN' needed!"
    exit 1
else
    PYTHON=`which "$PYTHON_BIN"`
    echo "> Using '$PYTHON' binary."
fi

SCRIPT_DIR_RELATIVE=`dirname "$0"`
SCRIPT_DIR_ABSOLUTE=`cd "$SCRIPT_DIR_RELATIVE"; pwd`

VENV_DIR="$HOME/.dotfiles-venv"

echo "> Using virtual environment in '$VENV_DIR'."

$PYTHON -m venv "$VENV_DIR"
. "$VENV_DIR/bin/activate"
pip install --upgrade setuptools pip
pip install --upgrade dotdrop

cd $SCRIPT_DIR_ABSOLUTE
dotdrop $@
