export ZSH="${HOME}/.oh-my-zsh"
export SHELL="$(which zsh)"
ZSH_THEME="dracula"
# SETTINGS
DISABLE_UPDATE_PROMPT="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
# PLUGINS
plugins=(
    cargo
    colored-man-pages
    colorize
    common-aliases
    docker
    docker-compose
    fancy-ctrl-z
    git
    git-auto-fetch
    git-extras
    gitfast
    golang
    gpg-agent
    history
    httpie
    magic-enter
    pip
    rust
    safe-paste
    timer
    tmux
    web-search
    vi-mode
    z
)
# INIT
source $ZSH/oh-my-zsh.sh
# CUSTOM
zstyle ':completion:*' rehash true
# ENVIRONMENT
export PATH="${HOME}/.scripts:${HOME}/.bin:${PATH}"
export EDITOR="vim"
export GIT_PAGER="cat"
export GOPATH="${HOME}/.go"
# ALIAS
alias open="xdg-open ${@}"
# FIX WSL UMASK
if [[ "$(umask)" = "0000" ]]; then umask 0022; fi
# LOCAL ADDITIONS
if [[ -r "${HOME}/.zshrc_local"  ]]; then source "${HOME}/.zshrc_local"; fi
eval `dircolors ${HOME}/.dircolors`

if [[ $(ps -p $PPID | egrep "^.*[${NO_TMUX_APPS}]\$" &>/dev/null) != 0 ]]; then
    ZSH_TMUX_AUTOSTART="true"
    ZSH_TMUX_AUTOSTART_ONCE="true"
    ZSH_TMUX_AUTOCONNECT="true"
fi
